apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
stringData:
  ADMIN_API_KEY: "z8kEZ9CXEEOQSJyn0BCVgqNi2Gjw+VlkB0/BXKjq2kk="
  READONLY_API_KEY: "m+PTe87QXohO3yPzdy0kRvOGdsWpIpzWeO/8cLApnhQ="